FROM python:3.12.11-bookworm

WORKDIR /app

COPY requirements.txt .
RUN pip install uv --no-cache-dir
RUN uv pip install --no-cache-dir --system -r requirements.txt
RUN rm requirements.txt
COPY ./app ./app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]